version: '3'
services:
    flask:
        hostname: flask
        image: "oakland/flask"
        ports:
            - "5000:5000"
        links:
            - mongo:mongo
            - redis:redis
    sockets:
        hostname: sockets
        image: "oakland/sockets"
        ports:
            - "5001:5001"
        links:
            - mongo:mongo
            - redis:redis
    vue:
        hostname: vue
        image: "oakland/vue"
        ports:
            - "8080:8080"
    mongo:
        image: "mongo:latest"
    redis:
        image: "redis:alpine"
    web:
        image: "nginx:stable-alpine"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        links:
            - vue
